export const ELEMENTSNAT = {

    PrimeiroNome : "div.natds2 div.natds75 div.MuiPaper-root.natds76.MuiPaper-elevation1.MuiPaper-rounded div.MuiBox-root.natds90.natds77:nth-child(1) div.MuiFormControl-root.natds91.natds78:nth-child(2) div.MuiFormControl-root.natds91 div.MuiInputBase-root.MuiInput-root.natds96.natds97.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input",
    Sobrenome : "div.natds2 div.natds75 div.MuiPaper-root.natds76.MuiPaper-elevation1.MuiPaper-rounded div.MuiBox-root.natds90.natds77:nth-child(1) div.MuiFormControl-root.natds91.natds78:nth-child(3) div.MuiFormControl-root.natds91 div.MuiInputBase-root.MuiInput-root.natds96.natds100.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input",
    email : ".natds83 > :nth-child(2) > :nth-child(1) > .MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input",
    campoSenha : "#password-field",
    campoRepitaSenha : "#confirmPassword-field",
    campoCpf : "div.natds2 div.natds75 div.MuiPaper-root.natds76.MuiPaper-elevation1.MuiPaper-rounded div.MuiBox-root.natds90.natds77:nth-child(1) div.MuiFormControl-root.natds91.natds78:nth-child(8) div.MuiFormControl-root.natds91 div.MuiInputBase-root.MuiInput-root.natds96.natds119.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input",
    campoDataNasc : "div.natds2 div.natds75 div.MuiPaper-root.natds76.MuiPaper-elevation1.MuiPaper-rounded div.MuiBox-root.natds90.natds77:nth-child(1) div.MuiFormControl-root.natds91.natds78:nth-child(9) div.MuiFormControl-root.natds91 div.MuiInputBase-root.MuiInput-root.natds96.natds121.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input",
    generoNaoEspecNatura : "div.natds2 div.natds75 div.MuiPaper-root.natds76.MuiPaper-elevation1.MuiPaper-rounded div.MuiBox-root.natds90.natds77:nth-child(1) div.MuiFormControl-root.natds91.natds78:nth-child(10) div.MuiFormGroup-root.natds82 label.MuiFormControlLabel-root:nth-child(3) span.MuiButtonBase-root.MuiIconButton-root.natds103.MuiRadio-root.MuiRadio-colorPrimary.MuiIconButton-colorPrimary span.MuiIconButton-label > input.natds106",
    campoTelefone : "div.natds2 div.natds75 div.MuiPaper-root.natds76.MuiPaper-elevation1.MuiPaper-rounded div.MuiBox-root.natds90.natds77:nth-child(1) div.MuiFormControl-root.natds91.natds78:nth-child(11) div.MuiFormControl-root.natds91 div.MuiInputBase-root.MuiInput-root.natds96.natds137.MuiInputBase-formControl.MuiInput-formControl > input.MuiInputBase-input.MuiInput-input",
    btnAceptTerm: "#acceptedterms"

}